apiVersion: v1
kind: PodTemplate
metadata:
  name: consul-podtemplate
  labels:
    app: consul
template:
  metadata:
    labels:
      app: consul
  spec:
    containers:
    - name: consul
      image: consul:latest
      args:
        - "agent"
        - "-server"
        - "-bootstrap-expect=1"
        - "-ui"
        - "-client=0.0.0.0"
      ports:
      - containerPort: 8500
        name: http
      - containerPort: 8600
        name: dns
      - containerPort: 8300
        name: server
      - containerPort: 8301
        name: serf-lan
      - containerPort: 8302
        name: serf-wan