apiVersion: rolloutsplugin.io/v1alpha1
kind: RolloutPlugin
metadata:
  name: rolloutplugin-sample
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  plugin:
    name: statefulset
    url: http://localhost:8080
    sha256: "1234567890"
  strategy:
    type: Canary
    canary:
      trafficRouting: 
        istio:
          virtualService: 
            name: istio-subset-split-vsvc
            routes:
            - primary
          destinationRule:
            name: istio-subset-split-destrule
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
      - setWeight: 10
      - pause: {}
      - setWeight: 20
      - pause: {}
      - setWeight: 30


