apiVersion: rolloutsplugin.io/v1alpha1
kind: RolloutPlugin
metadata:
  name: rolloutplugin-sample1
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  plugin:
    name: statefulset
    url: "https://helmchartsglobal.s3.us-east-1.amazonaws.com/"
    sha256: "d87216f6ab1730ad7703a3d6472ebbb2b5f7badbb438de0319b8edc1f4cc3802"
    verify: false
  strategy:
    type: Canary
    canary:
      trafficRouting: 
        istio:
          virtualService: 
            name: istio-subset-split-vsvc
            routes:
            - primary
          destinationRule:
            name: istio-subset-split-destrule
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
      - setWeight: 10
      - pause: {}
      - setWeight: 20
      - pause: {}
      - setWeight: 30


